services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health

    envVars:
      - key: NODE_VERSION
        value: 16.13.0
      - key: NODE_ENV
        value: production

databases:
  - name: strapi
    plan: starter
